# Generated by Django 2.1 on 2019-12-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('courseno', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
    ]
